version: '3.7'

services:

  terraform-shell:
    image: hashicorp/terraform
    container_name: terraform-shell
    volumes:
      - ./terraform:/playground
    working_dir: /playground
    entrypoint: /bin/ash
    tty: true
    depends_on:
      - keycloak
      - vault
    networks:
      - keycloak
    environment:
     - TF_CLI_CONFIG_FILE=/playground/terraform.tfrc

  keycloak:
    image: quay.io/keycloak/keycloak
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    command:
      - start-dev
    environment:
     - KEYCLOAK_ADMIN=root
     - KEYCLOAK_ADMIN_PASSWORD=root
     - KC_HOSTNAME_URL=http://localhost:8080
    ports:
     - 8080:8080
    networks:
      - keycloak

  vault:
    image: hashicorp/vault
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8200/ui/vault/auth" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    networks:
      - keycloak

networks:
  keycloak:
